version: "3.9"

services:  
  
  api:
    container_name: erp_middleware
    build: .
    restart: always    
    ports:
      - 5001:8001      
    environment:
      - ASPNETCORE_HTTP_PORTS=8001
        
