services:

  api:
    container_name: erp_middleware
    build: .
    restart: always
    ports:
      - 5001:8001
    environment:
      - ASPNETCORE_HTTP_PORTS=8001
    volumes:
      - app-storage:/app/app_data

volumes:
  app-storage:
